### ISSUE TITLE
Check if ya-runtime-vm works on windows after VOLUME changes

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-vm#104]
What:
- [x] Test solution with adding mounting VOLUMES options (https://github.com/golemfactory/ya-runtime-vm/pull/99#issuecomment-903296077)
If above doesn't work:
- [x] Consider copy content of VOLUMEs

**Comment by mfranciszkiewicz** [comment]
Volume options were pushed to https://github.com/golemfactory/ya-runtime-vm/tree/mf/fs-volume-overlayfs, solving the UX issue on Linux. The Windows version cannot be (thoroughly) tested and needs to be postponed until further notice.

Copying VOLUME contents may serve as a temporary workaround, which IMO should be avoided. It introduces additional overhead for starting up the VM, which may be significant depending on amount of data that needs to be copied and requires additional (accumulating) disk space. To properly solve this issue, we need a cross-platform 9p file server.

Available options for now:
1. https://github.com/golemfactory/ya-runtime-vm/tree/mf/fs-volume-overlayfs
   Merging will solve both root fs and volume issues on Linux but will make things harder with a Windows release.

2. https://github.com/golemfactory/ya-runtime-vm/pull/100 
   Increases the amount of data that can be written  to the root filesystem but does not address the issue with volumes.
