### ISSUE TITLE
Research 9p file server integration with the VM runtime

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-vm#109]
What:
- research on how to integrate the 9p file server with the VM runtime
- design

Why:
- 9p file server will provide better means of mounting directories by expanding the fixed-size filesystem root (in tmpfs) and allow for exposing the existing contents of volume directories
- 9p file server is cross-platform, which would allow to port the VM runtime to Windows

**Comment by prekucki** [comment]
[qemu-system-x86_64.zip](https://github.com/golemfactory/ya-runtime-vm/files/7928040/qemu-system-x86_64.zip)

**Comment by prekucki** [comment]
```bat
qemu-system-x86_64.exe -m 1G -nographic -vga none -kernel vmlinuz-virt ^
 -initrd initramfs.cpio.gz -net none -smp 2 ^
 -append "console=ttyS0 panic=1" -device virtio-serial ^
 -device virtio-rng-pci ^
 -chardev socket,id=manager_cdev,host=127.0.0.1,port=9003,server,nowait ^
 -chardev socket,id=net_cdev,host=127.0.0.1,port=9004,server,nowait ^
 -device virtserialport,chardev=manager_cdev,name=manager_port ^
 -device virtserialport,chardev=net_cdev,name=net_port ^
 -drive file=ubuntu.gvmi,cache=unsafe,readonly=on,format=raw,if=virtio ^
 -no-reboot -accel whpx  -nodefaults --serial stdio
 ```

**Comment by pwalski** [comment]
It  is a part of open PR https://github.com/golemfactory/ya-runtime-vm/pull/121
