### ISSUE TITLE
missing some cpu capabilities flags in "golem.inf.cpu.capabilities"

### ISSUE THREAD

**Issue by jedbrooke** [golemfactory/ya-runtime-vm#115]
some flags such as `avx2`, `bmi1`, `bmi2` are missing from the list in "golem.inf.cpu.capabilities"

running 
```rust
let cpu = CpuInfo::try_new().unwrap();
println!("{:?}",cpu.capabilities);
```
on my local machine produced the correct flags, but some flags are missing from the list from the API

**Comment by mfranciszkiewicz** [comment]
resolved by #111; release pending
