### ISSUE TITLE
Merge simplest version of VM support for Windows

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ya-runtime-vm#141]
- [x] clean things up 
- [x] fix most recent merge conflicts
- [ ] test
- [ ] new patches conflicts
- [ ] fix or temporarily remove examples
- [ ] merge

**Comment by kamirr** [comment]
Team decision to not spend any more time on Windows support, the initial motivation was knowledge transfer from Marek, and that is now complete. Having and maintaining support for Windows is not part of our goals for now.

I pushed confllict resolution to the open PR.
