### ISSUE TITLE
make a RC in ya-runtime-vm repo

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ya-runtime-vm#144]

**Comment by wkargul** [comment]
1. Open https://github.com/golemfactory/ya-runtime-vm/releases and check the latest release tag.
2. For ex. if the latest RC is v0.3.0-rc2 and you would like to release the next RC you have to tag the relevant commit with:
```
git tag pre-rel-v0.3.0-rc3 
```
3. Push it to origin
```
git push origin pre-rel-v0.3.0-rc3 
```
4. The automatic script will build artifacts automatically
