### ISSUE TITLE
Handle unknown arguments for commands

### ISSUE THREAD

**Issue by evik42** [golemfactory/ya-runtime-vm#149]
Handle unexpected / unknown arguments sent in a API command.

Currently if a command is sent to the ya-runtime-vm it will silently ignore any flags, parameters passed in the command that it does not recognizes.
This is a problem when the parameter/flag changes the behavior of the command (for example the `start-entrypoint` flag for `Start` command).
Unknown, unexpected flags/parameters in the command should cause an error as the runtime does not know how to fulfill the request.

**Comment by nieznanysprawiciel** [comment]
@evik42 Can you explain more?

**Comment by evik42** [comment]
edited description
