### ISSUE TITLE
Create GPU DEV Environment

### ISSUE THREAD

**Issue by golmek** [golemfactory/ya-runtime-vm#156]
**Prerequisites:**

- Devops need to prepare machine for Attila

**Acceptance Criteria:**

- Prepare Development Environment on provided machine

**Comment by evik42** [comment]
On imapp2029 I was able to compile ya-runtime-vm and yagna. It also has docker so I think I can create images locally and develop ExeUnit/ya-runtime-vm for gpu related tasks.
