### ISSUE TITLE
Create GPU/PCI Capability Namespace Proposal

### ISSUE THREAD

**Issue by golmek** [golemfactory/ya-runtime-vm#158]
**Acceptance Criteria:**

- Write capability (experimental) namespace proposal for GPU/PCI information in the Offer
   - It should be umbrella type of namespace which can be used to accommodate GPU/PCI needs of current GPU integration as well as extended for some potential future needs.
- Namespace proposal in documented in transparent way (GAP repository?)
- The goal is not to list every property, but to properties design structure

**Additional Information:**
- experimental feature (as described in GAP-32)

**Comment by evik42** [comment]
PCI passthrough is not specific to GPUs, the GAP should take into consideration all [PCI device classes](https://pci-ids.ucw.cz/read/PD/).

**Comment by evik42** [comment]
We do not need a full GAP as we will use experimental namespace, just document it somewhere.

**Comment by pwalski** [comment]
Related issue https://github.com/orgs/golemfactory/projects/30/views/7?pane=issue&itemId=25814410

**Comment by staszek-krotki** [comment]
GAP PR: https://github.com/golemfactory/golem-architecture/pull/86
