### ISSUE TITLE
ya-runtime-vm offer-template may print trailing garbage

### ISSUE THREAD

**Issue by kamirr** [golemfactory/ya-runtime-vm#177]
Random bytes are sometimes appended to stdout *after* the valid json is printed, when the program shuts down.

Currently worked around in https://github.com/golemfactory/yagna/pull/2769, to be reverted when the fundamental issue is addressed.

**Comment by scx1332** [comment]
Extra bytes appears once in 5-20 times depending on luck. For me it was 7 extra bytes with no apparent meaning.
