### ISSUE TITLE
Documentation: add required dependencies to README

### ISSUE THREAD

**Issue by hasezoey** [golemfactory/ya-runtime-vm#84]
from what i found at least `musl-tools` (or `musl-dev`?) must be installed (on an ubuntu-based system)

PS: and an section about how it install it (in what directory) would also be good to know

**Comment by mfranciszkiewicz** [comment]
Hello @hasezoey, thanks for pointing out the issue. I'll expand the README file to include prerequisites and building steps.

If you're running Ubuntu, it should be enough to run:

```bash
sudo apt install musl musl-tools
```

**Comment by hasezoey** [comment]
@mfranciszkiewicz followed the steps, installed with `cargo deb`, but now getting `Permission Error` (none of the files in `ya-runtime-vm/runtime` have `x` (execute bit) - which of those files will need it?
