### ISSUE TITLE
Linux-virt package used in init-container 

### ISSUE THREAD

**Issue by ControlCplusControlV** [golemfactory/ya-runtime-vm#85]
So the Makefile found in ya-runtime-vm/runtime/init-container/ has a bad target. Line 13 targets a no longer working link, and can't download anything from it because I am pretty sure alpine moved their package distro server. I looked for the current package location and think this this file may be the correct replacement

https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/linux-virt-5.10.29-r0.apk

Haven't managed to get that makefile to compile though, changing that target I still running into issues with the string of the cp commands not being able to locate the file path it copies files to. I figure thats an extraction issue from the download link though so it may all be the same issue.

**Comment by mfranciszkiewicz** [comment]
Please try out the `mf/stable-kernel-url` branch (#86)
